# The port to be used by Quarkus (default to 8080 if not specified)
#quarkus.http.port=9080

# Database configuration
quarkus.datasource.db-kind=h2
# Switch to this JDBC URL if you want to keep changes made to your DB
#   between service restarts. By default, the file will be generated
#   under the (unix) user's home directory, provide a new path if you
#   prefer.
#quarkus.datasource.jdbc.url=jdbc:h2:file:~/quarkus-h2-db;DB_CLOSE_DELAY=-1
quarkus.datasource.jdbc.url=jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
quarkus.datasource.jdbc.max-size=16
# Switch to this database generation mechanism if you want to keep
#   changes made to your DB instead of recreating it from scratch
#   each time the service is started
#quarkus.hibernate-orm.database.generation=create
quarkus.hibernate-orm.database.generation=drop-and-create
# This file is used to populate the DB at startup time with some rows.
#   Feel free to edit as you prefer, even adding new rows.
#   If you are willing to add/remove rows, adjust the sequence number
#   accordingly to avoid "ID already exists" errors!
quarkus.hibernate-orm.sql-load-script=initial-load.sql


# Export configuration: where do you want to save the generated file?
greenbank.export-to-file.path=/home/greentech/greenbank_exported_file.txt


# --- YOU DON'T NEED TO CHANGE CONFIGURATION BELOW THIS LINE ---

# Quarkus banner
quarkus.banner.path=greenbank_banner.txt

# Which kind of package to generate
quarkus.package.jar.type=uber-jar

# Smallrye OpenApi configuration
quarkus.smallrye-openapi.info-title=GreenBank API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=A set of API to be used in bootcamp demo

# Enable Swagger UI also in prod environment
quarkus.swagger-ui.always-include=true

# Increasing the transaction manager timeout to avoid exceptions on long runs
quarkus.transaction-manager.default-transaction-timeout=10m